[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.6
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 13

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

# theme
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

